package ru.yandex.practicum.filmorate;

import lombok.RequiredArgsConstructor;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.test.context.TestPropertySource;
import ru.yandex.practicum.filmorate.model.Film;
import ru.yandex.practicum.filmorate.storage.Rating;
import ru.yandex.practicum.filmorate.storage.database.DbFilmStorage;

import java.time.LocalDate;
import java.util.List;

import static org.assertj.core.api.AssertionsForClassTypes.assertThat;

@SpringBootTest
@TestPropertySource(properties = {
        "spring.sql.init.mode=never"
})
@RequiredArgsConstructor(onConstructor_ = @Autowired)
class DbFilmStorageTests {

    private final DbFilmStorage filmStorage;
    private final JdbcTemplate jdbcTemplate;

    @BeforeEach
    void setUp() {
        try {
            jdbcTemplate.execute("DROP TABLE films");
        } catch (Exception ignored) {

        }

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS ratings (
                    rating_id INT PRIMARY KEY,
                    name VARCHAR(10) NOT NULL
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS genres (
                    genre_id INT PRIMARY KEY,
                    name VARCHAR(50) NOT NULL
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS films (
                    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(255) NOT NULL,
                    description VARCHAR(200),
                    "releaseDate" DATE NOT NULL,
                    duration INT NOT NULL,
                    rating_id INT NOT NULL
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS film_likes (
                    film_id BIGINT NOT NULL,
                    user_id BIGINT NOT NULL
                )
                """);

        jdbcTemplate.execute("""
                CREATE TABLE IF NOT EXISTS film_genres (
                    film_id BIGINT NOT NULL,
                    genre_id INT NOT NULL
                )
                """);

        jdbcTemplate.update("DELETE FROM film_likes");
        jdbcTemplate.update("DELETE FROM film_genres");
        jdbcTemplate.update("DELETE FROM films");
        jdbcTemplate.update("DELETE FROM ratings");
        jdbcTemplate.update("DELETE FROM genres");

        jdbcTemplate.execute("ALTER TABLE films ALTER COLUMN film_id RESTART WITH 1");

        jdbcTemplate.update("INSERT INTO ratings (rating_id, name) VALUES (1, 'G')");
        jdbcTemplate.update("INSERT INTO ratings (rating_id, name) VALUES (2, 'PG')");
        jdbcTemplate.update("INSERT INTO ratings (rating_id, name) VALUES (3, 'PG-13')");
        jdbcTemplate.update("INSERT INTO ratings (rating_id, name) VALUES (4, 'R')");
        jdbcTemplate.update("INSERT INTO ratings (rating_id, name) VALUES (5, 'NC-17')");

        jdbcTemplate.update("INSERT INTO genres (genre_id, name) VALUES (1, 'Комедия')");
        jdbcTemplate.update("INSERT INTO genres (genre_id, name) VALUES (2, 'Драма')");
    }


    @Test
    void testCreateAndGetFilm() {
        Film film = new Film();
        film.setName("Test film");
        film.setDescription("Desc");
        film.setReleaseDate(LocalDate.of(2000, 1, 1));
        film.setDuration(120);
        film.setMpa(new Rating(1, "G"));

        Film created = filmStorage.addFilmInStorage(film);

        assertThat(created.getId()).isEqualTo(1L);

        Film fromDb = filmStorage.getFilmFromStorage(1L);
        assertThat(fromDb.getName()).isEqualTo("Test film");
    }

    @Test
    void testUpdateFilm() {
        Film film = new Film();
        film.setName("Old");
        film.setDescription("Old desc");
        film.setReleaseDate(LocalDate.of(2000, 1, 1));
        film.setDuration(100);
        film.setMpa(new Rating(1, "G"));
        Film created = filmStorage.addFilmInStorage(film);

        created.setName("New name");
        created.setDuration(150);

        Film updated = filmStorage.updateFilmInStorage(created);

        assertThat(updated.getName()).isEqualTo("New name");
        assertThat(updated.getDuration()).isEqualTo(150);
    }

    @Test
    void testGetAllFilms() {
        Film film1 = new Film();
        film1.setName("newName1");
        film1.setDescription("someDesc1");
        film1.setReleaseDate(LocalDate.of(1998, 3, 1));
        film1.setDuration(180);
        film1.setMpa(new Rating(2, "PG"));

        Film film2 = new Film();
        film2.setName("newName2");
        film2.setDescription("someDesc2");
        film2.setReleaseDate(LocalDate.of(1996, 7, 5));
        film2.setDuration(240);
        film2.setMpa(new Rating(3, "PG-13"));

        filmStorage.addFilmInStorage(film1);
        filmStorage.addFilmInStorage(film2);

        var all = filmStorage.getAllFilmsFromStorage();

        assertThat(all.size()).isEqualTo(2);
    }


    @Test
    void testGetPopularFilmsEmpty() {
        List<Film> popular = filmStorage.getPopular(10);

        assertThat(popular.isEmpty());
    }
}
